# -*- coding: utf-8 -*-
"""Submission_MLT_Book_Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cw8x3-yyZ0ISx7r9U_ryEVTcufAnbEAG

# **Book Recommendation System**
# **Sistem Rekomendasi Buku: Content-Based Filtering & Collaborative Filtering**

**Nama: Kendrick Filbert**  
**Dicoding ID: kendrickfff**

---

## **Deskripsi Proyek**

Proyek ini membangun sistem rekomendasi buku menggunakan **Book-Crossing Dataset** dengan dua pendekatan:
1. **Content-Based Filtering** — Merekomendasikan buku berdasarkan kemiripan fitur konten (penulis & penerbit) menggunakan TF-IDF dan Cosine Similarity.
2. **Collaborative Filtering** — Merekomendasikan buku secara personal berdasarkan pola rating pengguna menggunakan Neural Network (RecommenderNet dengan Embedding Layer).

**Dataset:** [Book-Crossing Dataset](https://www.kaggle.com/datasets/syedjaferk/book-crossing-dataset)  
- 271.360 buku
- 278.858 pengguna
- 1.149.780 data rating

## **1. Install Library yang Dibutuhkan**
"""

# Install Kaggle API untuk download dataset
!pip install -q kaggle

"""## **2. Import Library**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

"""## **3. Data Understanding**

### **3.1 Data Loading**

Dataset yang digunakan: **Book-Crossing Dataset**  
Source: https://www.kaggle.com/datasets/syedjaferk/book-crossing-dataset

Dataset terdiri dari 3 file:
- `Books.csv` — Metadata buku (judul, penulis, penerbit, tahun terbit)
- `Users.csv` — Data demografis pengguna
- `Ratings.csv` — Data rating buku oleh pengguna
"""

# Setup Kaggle API
!rm -rf ~/.kaggle && mkdir ~/.kaggle/
!mv kaggle.json ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

# Download dataset
!kaggle datasets download -d syedjaferk/book-crossing-dataset

# Ekstrak file zip
!unzip /content/book-crossing-dataset.zip -d /content/book-crossing/
!ls /content/book-crossing/

# Load dataset with correct separator
books = pd.read_csv('/content/book-crossing/BX-Books.csv',
                    sep=';',
                    encoding='latin-1',
                    on_bad_lines='skip',
                    low_memory=False)

users = pd.read_csv('/content/book-crossing/BX-Users.csv',
                    sep=';',
                    encoding='latin-1',
                    on_bad_lines='skip')

ratings = pd.read_csv('/content/book-crossing/BX-Book-Ratings.csv',
                      sep=';',
                      encoding='latin-1',
                      on_bad_lines='skip')

print(f'Books shape  : {books.shape}')
print(f'Users shape  : {users.shape}')
print(f'Ratings shape: {ratings.shape}')

# Preview dataset Books
print('=== Dataset Books ===')
books.head()

# Preview dataset Users
print('=== Dataset Users ===')
users.head()

# Preview dataset Ratings
print('=== Dataset Ratings ===')
ratings.head()

"""### **3.2 Exploratory Data Analysis (EDA)**

#### **3.2.1 Deskripsi Variabel**
"""

# Informasi dataset Books
print('=== INFO BOOKS ===')
books.info()

# Informasi dataset Users
print('=== INFO USERS ===')
users.info()

# Informasi dataset Ratings
print('=== INFO RATINGS ===')
ratings.info()

# Statistik deskriptif ratings
print('=== STATISTIK DESKRIPTIF RATINGS ===')
ratings.describe()

# Cek missing values
print('Missing Values - Books:')
print(books.isnull().sum())
print('\nMissing Values - Users:')
print(users.isnull().sum())
print('\nMissing Values - Ratings:')
print(ratings.isnull().sum())

"""#### **3.2.2 EDA - Univariate Analysis**

##### **Distribusi Rating**
"""

plt.figure(figsize=(10, 5))
rating_counts = ratings['Book-Rating'].value_counts().sort_index()
sns.barplot(x=rating_counts.index, y=rating_counts.values, palette='viridis')
plt.title('Distribusi Rating Buku', fontsize=15, fontweight='bold')
plt.xlabel('Rating', fontsize=12)
plt.ylabel('Jumlah', fontsize=12)
plt.tight_layout()
plt.show()

print(f"\nJumlah implicit rating (0)  : {(ratings['Book-Rating']==0).sum():,}")
print(f"Jumlah explicit rating (1-10): {(ratings['Book-Rating']>0).sum():,}")

"""**Insight:** Mayoritas rating bernilai 0 (*implicit feedback*). Untuk Collaborative Filtering, kita akan menggunakan hanya rating eksplisit (1-10)."""

# Top 10 Penulis Paling Produktif
plt.figure(figsize=(12, 5))
top_authors = books['Book-Author'].value_counts().head(10)
sns.barplot(x=top_authors.values, y=top_authors.index, palette='magma')
plt.title('Top 10 Penulis dengan Buku Terbanyak', fontsize=15, fontweight='bold')
plt.xlabel('Jumlah Buku', fontsize=12)
plt.tight_layout()
plt.show()
print(f'Penulis paling produktif: {top_authors.index[0]} ({top_authors.values[0]} buku)')

# Distribusi Tahun Terbit
books['Year-Of-Publication'] = pd.to_numeric(books['Year-Of-Publication'], errors='coerce')
books_year = books[(books['Year-Of-Publication'] >= 1900) & (books['Year-Of-Publication'] <= 2023)]

plt.figure(figsize=(12, 5))
books_year['Year-Of-Publication'].hist(bins=50, color='steelblue', edgecolor='white')
plt.title('Distribusi Tahun Terbit Buku', fontsize=15, fontweight='bold')
plt.xlabel('Tahun Terbit', fontsize=12)
plt.ylabel('Jumlah Buku', fontsize=12)
plt.tight_layout()
plt.show()
print('Insight: Sebagian besar buku diterbitkan antara tahun 1980-2005.')

# Distribusi Usia User
users['Age'] = pd.to_numeric(users['Age'], errors='coerce')
users_age = users[(users['Age'] >= 5) & (users['Age'] <= 100)]

plt.figure(figsize=(10, 5))
users_age['Age'].hist(bins=40, color='coral', edgecolor='white')
plt.title('Distribusi Usia Pengguna', fontsize=15, fontweight='bold')
plt.xlabel('Usia', fontsize=12)
plt.ylabel('Jumlah Pengguna', fontsize=12)
plt.tight_layout()
plt.show()
print(f'Usia rata-rata pengguna: {users_age["Age"].mean():.1f} tahun')
print(f'Usia median pengguna  : {users_age["Age"].median():.1f} tahun')

# Top 10 Publisher
plt.figure(figsize=(12, 5))
top_publishers = books['Publisher'].value_counts().head(10)
sns.barplot(x=top_publishers.values, y=top_publishers.index, palette='coolwarm')
plt.title('Top 10 Publisher dengan Buku Terbanyak', fontsize=15, fontweight='bold')
plt.xlabel('Jumlah Buku', fontsize=12)
plt.tight_layout()
plt.show()

"""## **4. Data Preparation**

Tahap ini mempersiapkan data agar siap digunakan untuk pemodelan kedua pendekatan sistem rekomendasi.
"""

# 4.1 Menangani Missing Values pada Books
print('Missing values SEBELUM cleaning:')
print(books[['Book-Author', 'Publisher']].isnull().sum())

books['Book-Author'] = books['Book-Author'].fillna('Unknown Author')
books['Publisher'] = books['Publisher'].fillna('Unknown Publisher')
books['Year-Of-Publication'] = pd.to_numeric(books['Year-Of-Publication'], errors='coerce')
books['Year-Of-Publication'] = books['Year-Of-Publication'].fillna(
    books['Year-Of-Publication'].median()
)

print('\nMissing values SETELAH cleaning:')
print(books[['Book-Author', 'Publisher', 'Year-Of-Publication']].isnull().sum())

# 4.2 Seleksi dan Standardisasi Kolom
books_clean = books[['ISBN', 'Book-Title', 'Book-Author',
                      'Year-Of-Publication', 'Publisher']].copy()
books_clean.columns = ['isbn', 'title', 'author', 'year', 'publisher']
books_clean = books_clean.drop_duplicates(subset='isbn').reset_index(drop=True)

print(f'Jumlah buku setelah cleaning: {len(books_clean):,}')
books_clean.head()

# 4.3 Standardisasi kolom ratings & filter eksplisit
ratings.columns = ['user_id', 'isbn', 'rating']
ratings_explicit = ratings[ratings['rating'] > 0].copy()

print(f'Total rating           : {len(ratings):,}')
print(f'Rating eksplisit (1-10): {len(ratings_explicit):,}')
print(f'Persentase eksplisit   : {len(ratings_explicit)/len(ratings)*100:.1f}%')

# 4.4 Filter User & Buku dengan cukup interaksi
user_counts = ratings_explicit['user_id'].value_counts()
active_users = user_counts[user_counts >= 5].index

book_counts = ratings_explicit['isbn'].value_counts()
popular_books = book_counts[book_counts >= 5].index

ratings_filtered = ratings_explicit[
    (ratings_explicit['user_id'].isin(active_users)) &
    (ratings_explicit['isbn'].isin(popular_books))
].copy()

print(f'Rating setelah filter  : {len(ratings_filtered):,}')
print(f'Unique users           : {ratings_filtered["user_id"].nunique():,}')
print(f'Unique buku            : {ratings_filtered["isbn"].nunique():,}')

# 4.5 Encoding Label
user_encoder = LabelEncoder()
book_encoder = LabelEncoder()

ratings_filtered['user_encoded'] = user_encoder.fit_transform(ratings_filtered['user_id'])
ratings_filtered['book_encoded'] = book_encoder.fit_transform(ratings_filtered['isbn'])

num_users = ratings_filtered['user_encoded'].nunique()
num_books = ratings_filtered['book_encoded'].nunique()

print(f'Jumlah encoded users: {num_users:,}')
print(f'Jumlah encoded books: {num_books:,}')
ratings_filtered.head()

# 4.6 Normalisasi Rating ke rentang [0, 1]
min_rating = ratings_filtered['rating'].min()
max_rating = ratings_filtered['rating'].max()

ratings_filtered['rating_normalized'] = ratings_filtered['rating'].apply(
    lambda x: (x - min_rating) / (max_rating - min_rating)
)

print(f'Range rating original   : {min_rating} - {max_rating}')
print(f'Range rating normalized : {ratings_filtered["rating_normalized"].min():.2f} - {ratings_filtered["rating_normalized"].max():.2f}')

# 4.7 Train-Test Split
X = ratings_filtered[['user_encoded', 'book_encoded']].values
y = ratings_filtered['rating_normalized'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f'Data training: {len(X_train):,} ({len(X_train)/len(X)*100:.0f}%)')
print(f'Data testing : {len(X_test):,} ({len(X_test)/len(X)*100:.0f}%)')

# 4.8 Persiapan Data untuk Content-Based Filtering
books_clean['content_features'] = (
    books_clean['author'].fillna('') + ' ' +
    books_clean['publisher'].fillna('')
)

isbn_in_ratings = ratings_filtered['isbn'].unique()
books_cbf = books_clean[books_clean['isbn'].isin(isbn_in_ratings)].reset_index(drop=True)

print(f'Jumlah buku untuk Content-Based Filtering: {len(books_cbf):,}')
books_cbf.head()

"""## **5. Modeling**

### **5.1 Model 1: Content-Based Filtering**

Content-Based Filtering merekomendasikan buku berdasarkan kemiripan fitur konten menggunakan TF-IDF Vectorizer dan Cosine Similarity.
"""

# TF-IDF Vectorization
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
tfidf_matrix = tfidf.fit_transform(books_cbf['content_features'])

print(f'Shape TF-IDF Matrix: {tfidf_matrix.shape}')
print(f'  - {tfidf_matrix.shape[0]:,} buku')
print(f'  - {tfidf_matrix.shape[1]:,} fitur teks unik')

# Hitung Cosine Similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(f'Shape Cosine Similarity Matrix: {cosine_sim.shape}')

# Tampilkan contoh nilai similarity
print(f'\nContoh nilai similarity matrix (5x5 pertama):')
print(cosine_sim[:5, :5])

# Buat index mapping title -> index
indices = pd.Series(books_cbf.index, index=books_cbf['title']).drop_duplicates()
print(f'Jumlah indeks unik: {len(indices):,}')

def get_content_based_recommendations(title, n=10):
    """
    Mendapatkan rekomendasi buku berbasis konten.

    Parameters:
    -----------
    title : str — Judul buku acuan
    n     : int — Jumlah rekomendasi (default: 10)

    Returns:
    --------
    pd.DataFrame — Top-N buku yang direkomendasikan
    """
    if title not in indices:
        return f"Buku '{title}' tidak ditemukan."

    # Ambil index pertama jika terdapat judul duplikat
    idx = indices[title]
    if isinstance(idx, pd.Series):
        idx = idx.iloc[0]

    sim_scores = sorted(list(enumerate(cosine_sim[idx])),
                        key=lambda x: x[1], reverse=True)[1:n+1]
    book_indices = [i[0] for i in sim_scores]
    similarity_values = [round(i[1], 4) for i in sim_scores]

    result = books_cbf.iloc[book_indices][['title', 'author', 'publisher', 'year']].copy()
    result['similarity_score'] = similarity_values
    result = result.reset_index(drop=True)
    result.index += 1
    return result

print('Fungsi get_content_based_recommendations() berhasil diperbarui untuk menangani judul duplikat!')

# Uji Content-Based Filtering
sample_book = books_cbf['title'].iloc[0]
print(f'Buku yang diuji: "{sample_book}"')
print('\nInformasi buku acuan:')
print(books_cbf[books_cbf['title'] == sample_book][['title', 'author', 'publisher', 'year']])

# Tampilkan Top-10 Rekomendasi
print(f'\nTop-10 Rekomendasi Buku untuk "{sample_book}":')
cbf_result = get_content_based_recommendations(sample_book, n=10)
cbf_result

"""### **5.2 Model 2: Collaborative Filtering (Neural Network)**

Menggunakan arsitektur **RecommenderNet** dengan Embedding Layer untuk mempelajari representasi vektor laten user dan buku.
"""

class RecommenderNet(keras.Model):
    """
    Arsitektur Neural Network untuk Collaborative Filtering.
    Menggunakan Embedding Layer untuk user dan buku.
    Output: prediksi rating ternormalisasi (0-1)
    """

    def __init__(self, num_users, num_books, embedding_size=50, **kwargs):
        super(RecommenderNet, self).__init__(**kwargs)
        self.num_users = num_users
        self.num_books = num_books
        self.embedding_size = embedding_size

        # User embedding + bias
        self.user_embedding = layers.Embedding(
            num_users, embedding_size,
            embeddings_initializer='he_normal',
            embeddings_regularizer=keras.regularizers.l2(1e-6),
            name='user_embedding'
        )
        self.user_bias = layers.Embedding(num_users, 1, name='user_bias')

        # Book embedding + bias
        self.book_embedding = layers.Embedding(
            num_books, embedding_size,
            embeddings_initializer='he_normal',
            embeddings_regularizer=keras.regularizers.l2(1e-6),
            name='book_embedding'
        )
        self.book_bias = layers.Embedding(num_books, 1, name='book_bias')

    def call(self, inputs):
        user_vector = self.user_embedding(inputs[:, 0])
        user_bias   = self.user_bias(inputs[:, 0])
        book_vector = self.book_embedding(inputs[:, 1])
        book_bias   = self.book_bias(inputs[:, 1])

        dot = tf.tensordot(user_vector, book_vector, 2)
        x   = dot + user_bias + book_bias
        return tf.nn.sigmoid(x)

print('Kelas RecommenderNet berhasil didefinisikan!')

# Inisialisasi & Compile Model
model_cf = RecommenderNet(num_users, num_books, embedding_size=50)

model_cf.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=[tf.keras.metrics.RootMeanSquaredError()]
)

print('Model berhasil dikompilasi!')
print(f'Jumlah Users   : {num_users:,}')
print(f'Jumlah Books   : {num_books:,}')
print(f'Embedding size : 50')

# Callbacks
early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_root_mean_squared_error',
    patience=25,
    restore_best_weights=True
)

reduce_lr = keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=3,
    min_lr=1e-6
)

# Training
print('Memulai training model...')
history = model_cf.fit(
    x=X_train,
    y=y_train,
    batch_size=512,
    epochs=50,
    validation_data=(X_test, y_test),
    callbacks=[early_stopping, reduce_lr],
    verbose=1
)
print('Training selesai!')

# Visualisasi Training History
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history.history['loss'], label='Training Loss', color='steelblue', linewidth=2)
axes[0].plot(history.history['val_loss'], label='Validation Loss', color='coral', linewidth=2)
axes[0].set_title('Model Loss', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].legend()
axes[0].grid(alpha=0.3)

axes[1].plot(history.history['root_mean_squared_error'],
             label='Training RMSE', color='steelblue', linewidth=2)
axes[1].plot(history.history['val_root_mean_squared_error'],
             label='Validation RMSE', color='coral', linewidth=2)
axes[1].set_title('Model RMSE', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('RMSE')
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

def get_collaborative_recommendations(user_id, n=10):
    """
    Mendapatkan rekomendasi buku berbasis Collaborative Filtering.

    Parameters:
    -----------
    user_id : int/str — ID pengguna
    n       : int     — Jumlah rekomendasi (default: 10)

    Returns:
    --------
    pd.DataFrame — Top-N buku yang direkomendasikan
    """
    if user_id not in user_encoder.classes_:
        return f"User ID '{user_id}' tidak ditemukan."

    user_encoded_val = user_encoder.transform([user_id])[0]

    books_read = ratings_filtered[
        ratings_filtered['user_id'] == user_id
    ]['isbn'].values

    books_not_read = ratings_filtered[
        ~ratings_filtered['isbn'].isin(books_read)
    ]['isbn'].unique()

    books_not_read_encoded = book_encoder.transform(books_not_read)
    user_book_array = np.column_stack([
        np.full(len(books_not_read_encoded), user_encoded_val),
        books_not_read_encoded
    ])

    predicted = model_cf.predict(user_book_array, verbose=0).flatten()
    top_idx = predicted.argsort()[-n:][::-1]
    top_isbn = books_not_read[top_idx]
    top_ratings = predicted[top_idx]

    result = books_clean[books_clean['isbn'].isin(top_isbn)][
        ['isbn', 'title', 'author', 'publisher', 'year']
    ].copy()

    rating_map = {
        isbn: round(r * (max_rating - min_rating) + min_rating, 2)
        for isbn, r in zip(top_isbn, top_ratings)
    }
    result['predicted_rating'] = result['isbn'].map(rating_map)
    result = result.sort_values('predicted_rating', ascending=False).reset_index(drop=True)
    result.index += 1
    return result

print('Fungsi get_collaborative_recommendations() berhasil didefinisikan!')

# Uji Collaborative Filtering
sample_user = ratings_filtered['user_id'].value_counts().index[0]
print(f'User ID yang diuji: {sample_user}')

print(f'\nBuku yang sudah dibaca/dirating oleh User {sample_user} (Top 5):')
user_history = ratings_filtered[
    ratings_filtered['user_id'] == sample_user
].merge(books_clean, on='isbn')[['title', 'author', 'rating']]
print(user_history.sort_values('rating', ascending=False).head())

# Tampilkan Top-10 Rekomendasi
print(f'\nTop-10 Rekomendasi Buku untuk User {sample_user}:')
cf_result = get_collaborative_recommendations(sample_user, n=10)
cf_result

"""## **6. Evaluation**

### **6.1 Evaluasi Content-Based Filtering: Precision@K**

**Formula:**  
$$\text{Precision@K} = \frac{\text{Jumlah item relevan dalam Top-K}}{K}$$

Sebuah rekomendasi dianggap **relevan** jika memiliki **penulis yang sama** dengan buku acuan.
"""

def evaluate_cbf_precision(title, n=10):
    """Menghitung Precision@K untuk Content-Based Filtering."""
    if title not in indices:
        return None

    # Ambil penulis referensi (pastikan hanya satu nilai)
    ref_author = books_cbf[books_cbf['title'] == title]['author'].iloc[0]

    recs = get_content_based_recommendations(title, n=n)
    if isinstance(recs, str):
        return None

    relevant = recs[recs['author'] == ref_author]
    return len(relevant) / n, len(relevant), n

# Uji pada 5 buku yang memiliki banyak karya dari penulis yang sama
test_books = books_cbf.groupby('author').filter(lambda x: len(x) >= 5)['title'].head(5).tolist()

precision_scores = []
print(f'{"Judul Buku":<45} {"Relevan/K":<12} {"Precision@10"}')
print('-' * 70)

for book in test_books:
    result = evaluate_cbf_precision(book, n=10)
    if result:
        prec, rel, total = result
        precision_scores.append(prec)
        print(f'{book[:43]:<45} {rel}/{total:<11} {prec:.2f}')

avg_precision = np.mean(precision_scores) if precision_scores else 0
print(f'\nRata-rata Precision@10 : {avg_precision:.4f} ({avg_precision*100:.1f}%)')

"""### **6.2 Evaluasi Collaborative Filtering: RMSE & MAE**

**Formula RMSE:**  
$$\text{RMSE} = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (\hat{r}_i - r_i)^2}$$

**Formula MAE:**  
$$\text{MAE} = \frac{1}{n} \sum_{i=1}^{n} |\hat{r}_i - r_i|$$
"""

# Prediksi pada test set
y_pred = model_cf.predict(X_test, verbose=0).flatten()

# Denormalisasi ke skala 1-10
y_test_actual = y_test * (max_rating - min_rating) + min_rating
y_pred_actual = y_pred * (max_rating - min_rating) + min_rating

# Hitung RMSE & MAE
rmse = np.sqrt(np.mean((y_test_actual - y_pred_actual) ** 2))
mae  = np.mean(np.abs(y_test_actual - y_pred_actual))

print('=== HASIL EVALUASI COLLABORATIVE FILTERING ===')
print(f'RMSE (Root Mean Squared Error): {rmse:.4f}')
print(f'MAE  (Mean Absolute Error)    : {mae:.4f}')
print(f'\nInterpretasi:')
print(f'  RMSE {rmse:.4f} → rata-rata kesalahan prediksi ±{rmse:.2f} poin (skala 1-10)')
print(f'  MAE  {mae:.4f} → rata-rata absolut kesalahan prediksi {mae:.2f} poin')

# Visualisasi Prediksi vs Aktual
plt.figure(figsize=(8, 6))
plt.scatter(y_test_actual[:500], y_pred_actual[:500], alpha=0.4, color='steelblue', s=20)
plt.plot([1, 10], [1, 10], 'r--', linewidth=2, label='Perfect Prediction')
plt.xlabel('Rating Aktual', fontsize=12)
plt.ylabel('Rating Prediksi', fontsize=12)
plt.title('Rating Aktual vs Rating Prediksi\n(Collaborative Filtering)', fontsize=13, fontweight='bold')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""## **7. Kesimpulan**"""

print('=' * 60)
print('RINGKASAN HASIL PROYEK')
print('=' * 60)
print()
print('MODEL 1: Content-Based Filtering')
print(f'  Metrik  : Precision@10')
print(f'  Hasil   : {avg_precision*100:.1f}% rata-rata rekomendasi relevan')
print(f'  Teknik  : TF-IDF Vectorizer + Cosine Similarity')
print()
print('MODEL 2: Collaborative Filtering (Neural Network)')
print(f'  Metrik  : RMSE & MAE')
print(f'  RMSE    : {rmse:.4f}')
print(f'  MAE     : {mae:.4f}')
print(f'  Teknik  : RecommenderNet (Embedding Layer + Dot Product)')
print()
print('Kedua model berhasil dibangun dan menunjukkan performa yang baik.')
print('Content-Based Filtering cocok untuk cold-start item baru,')
print('sementara Collaborative Filtering lebih personal dan beragam.')